Algoritmo "crescente"

Var
   x, y : inteiro

Inicio
      escreval("Digite 2 números")
      leia(x)
      leia(y)
      
      enquanto x <> y faca
               se x < y entao
                  escreval("CRESCENTE")
               senao
                  escreval("DESCRESCENTE")
               fimse
      escreval("Digite 2 números")
      leia(x)
      leia(y)
      fimenquanto



Fimalgoritmo